name: worldfunclub
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^3.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  json_annotation:
  rxdart: ^0.21.0
  fluttertoast: ^7.1.1
  flutter_swiper: ^1.1.6
  provider: ^4.3.2+2
  dartin: ^0.1.0
  shared_preferences: ^0.5.12+4
#  webviewpopupauth:
#    path: ../flutter_win_webview\webview_popupauth
  web_view_open:
    git:
      url: https://gitee.com/Tokra/web_view_open.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#---------------------------------------------------------------------------------------------------
  assets:
    - assets/region.json
    - images/2.0x/Cart.png
    - images/2.0x/Contact.png
    - images/2.0x/dpjx.png
    - images/2.0x/Favrite.png
    - images/2.0x/Footpoint.png
    - images/2.0x/G4.png
    - images/2.0x/ic_busi_bg.webp
    - images/2.0x/ic_busi_check.webp
    - images/2.0x/ic_busi_line.webp
    - images/2.0x/ic_cart.png
    - images/2.0x/ic_category.webp
    - images/2.0x/ic_club.webp
    - images/2.0x/ic_club_def.webp
    - images/2.0x/ic_fire.webp
    - images/2.0x/ic_home.webp
    - images/2.0x/ic_home_def.webp
    - images/2.0x/ic_local.webp
    - images/2.0x/ic_local_def.webp
    - images/2.0x/ic_message.png
    - images/2.0x/ic_message.webp
    - images/2.0x/ic_mine.webp
    - images/2.0x/ic_mine_def.webp
    - images/2.0x/ic_settings.png
    - images/2.0x/ic_shop.png
    - images/2.0x/ic_star.png
    - images/2.0x/ic_start_around.png
    - images/2.0x/ic_vip.webp
    - images/2.0x/ic_vip_def.webp
    - images/2.0x/LiveOrder.png
    - images/2.0x/Merchantmanagement.png
    - images/2.0x/mine.png
    - images/2.0x/pop.png
    - images/2.0x/pop2.png
    - images/2.0x/SignIn.png
    - images/2.0x/wechat.webp
    - images/2.0x/willEvaluation.png
    - images/2.0x/willPay.png
    - images/2.0x/willReceive.png
    - images/2.0x/willRefund.png
    - images/2.0x/willSend.png
    - images/3.0x/Cart.png
    - images/3.0x/Contact.png
    - images/3.0x/dpjx.png
    - images/3.0x/Favrite.png
    - images/3.0x/Footpoint.png
    - images/3.0x/G4.png
    - images/3.0x/ic_busi_bg.webp
    - images/3.0x/ic_busi_check.webp
    - images/3.0x/ic_busi_line.webp
    - images/3.0x/ic_cart.png
    - images/3.0x/ic_category.webp
    - images/3.0x/ic_club.webp
    - images/3.0x/ic_club_def.webp
    - images/3.0x/ic_fire.webp
    - images/3.0x/ic_home.webp
    - images/3.0x/ic_home_def.webp
    - images/3.0x/ic_local.webp
    - images/3.0x/ic_local_def.webp
    - images/3.0x/ic_message.png
    - images/3.0x/ic_message.webp
    - images/3.0x/ic_mine.webp
    - images/3.0x/ic_mine_def.webp
    - images/3.0x/ic_settings.png
    - images/3.0x/ic_shop.png
    - images/3.0x/ic_star.png
    - images/3.0x/ic_start_around.png
    - images/3.0x/ic_vip.webp
    - images/3.0x/ic_vip_def.webp
    - images/3.0x/LiveOrder.png
    - images/3.0x/Merchantmanagement.png
    - images/3.0x/mine.png
    - images/3.0x/pop.png
    - images/3.0x/pop2.png
    - images/3.0x/SignIn.png
    - images/3.0x/wechat.webp
    - images/3.0x/willEvaluation.png
    - images/3.0x/willPay.png
    - images/3.0x/willReceive.png
    - images/3.0x/willRefund.png
    - images/3.0x/willSend.png
    - images/Cart.png
    - images/Contact.png
    - images/dpjx.png
    - images/Favrite.png
    - images/Footpoint.png
    - images/G4.png
    - images/ic_busi_bg.webp
    - images/ic_busi_check.webp
    - images/ic_busi_line.webp
    - images/ic_cart.png
    - images/ic_category.webp
    - images/ic_club.webp
    - images/ic_club_def.webp
    - images/ic_fire.webp
    - images/ic_home.webp
    - images/ic_home_def.webp
    - images/ic_launcher.png
    - images/ic_local.webp
    - images/ic_local_def.webp
    - images/ic_message.png
    - images/ic_message.webp
    - images/ic_mine.webp
    - images/ic_mine_def.webp
    - images/ic_settings.png
    - images/ic_shop.png
    - images/ic_star.png
    - images/ic_start_around.png
    - images/ic_vip.webp
    - images/ic_vip_def.webp
    - images/LiveOrder.png
    - images/Merchantmanagement.png
    - images/mine.png
    - images/pop.png
    - images/pop2.png
    - images/SignIn.png
    - images/wechat.webp
    - images/willEvaluation.png
    - images/willPay.png
    - images/willReceive.png
    - images/willRefund.png
    - images/willSend.png




  #===================================================================================================
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
